---
title: ""
author: ""
date: ""
lang: es
bibliography: referencias.bib
csl: apa.csl

format:
  pdf:
    documentclass: article
    classoption: 12pt
    papersize: letter
    geometry:
      - margin=2.54cm
    linestretch: 2
    mainfont: "Times New Roman"
    fontsize: 12pt
    toc: false
    number-sections: false
    include-in-header:
      text: |
        \usepackage{setspace}
        \usepackage{indentfirst}
        \setlength{\parindent}{1.27cm}
        \usepackage{fancyhdr}
        \pagestyle{fancy}
        \fancyhf{}
        \rhead{\thepage}
        \renewcommand{\headrulewidth}{0pt}
        \usepackage{tikz}
        \usetikzlibrary{positioning}
        \usepackage{float}
---

\begin{titlepage}
\centering

\vspace*{5cm}

{\Large \textbf{Impacto de las reformas agrarias sobre la economía agrícola en Colombia: evidencia histórica de largo plazo (1925–2025)}}

\vspace{2cm}

Juan Diego Moreno Sánchez 

Universidad Externado de Colombia  

\vfill

\today

\end{titlepage}

\newpage

# Resumen

Al final

\newpage

# Introducción

Colombia históricamente se ha caracterizado por una fuerte economía agraria, la cual, durante la mayor parte del siglo XX fue el principal motor económico del país. A pesar de esto, Colombia ha presentado una de las mayores desigualdades en la tenencia de la tierra a nivel mundial en el presente siglo, con un Gini calculado de 0,89 [@gini_worldbank], un Gini de concentración extremadamente alto.

Esto no solo se limita a un problema de tenencia de la tierra; se expande a problemas de productividad de la tierra [@berry1979; @binswanger1995] y de conflicto armado por estas desigualdades estructurales [@deininger1999].

Durante el periodo de análisis (1925–2025), se presentaron múltiples intentos de reforma agraria orientados a solucionar estos problemas estructurales. El primer intento del siglo XX fue la Ley 200 de 1936, promulgada durante la segunda presidencia de Alfonso López Pumarejo . El segundo fue la Ley 135 de 1961, expedida en el contexto del Frente Nacional bajo la presidencia de Alberto Lleras Camargo. El tercer intento fue la Ley 160 de 1994, enmarcada en la Constitución de 1991 y promulgada durante la presidencia de César Gaviria Trujillo. Finalmente, el último esfuerzo relevante corresponde a la reforma agraria derivada del Acuerdo de Paz con las FARC-EP en 2016, durante la presidencia de Juan Manuel Santos Calderón.

La literatura económica ha documentado ampliamente una relación inversa entre la productividad de la tierra y concentración en la posesión de esta [@berry1979], así mismo se ha demostrado una relación positiva entre la concentración de la tierra y generación de conflictos armados [@deininger1999], esto resultados sugieren que la estructura de organización y propiedad de la tierra tienen implicaciones directas en la productividad del sector rural. En la literatura no existe un análisis amplio, basado en datos históricos y cuantificables mediante modelos econométricos, que nos permitan medir los impactos estructurales de las reformas agrarias en Colombia.

Además, existen planteamientos que proponer que la economía agrícola se ve afectada por factores como la demanda de alimentos y el precio de los alimentos, lo que lleva a incentivar a los productores a mejorar la productividad agrícola, lo que a su vez, lleva a un aumento en la producción agrícola [@ruttan_hayami_strategies]. 



Este documento contribuye en tres aspectos. Primero, en la construcción de una serie de tiempo de largo plazo del producto agropecuario y del consumo de los hogares en Colombia. Segundo, incorporando pruebas de quiebres estructurales [@perron1989 ,@chow1960]. Tercero, implementando el método de proyecciones locales [@jorda2005]. Cuarto, analizando la cointregación entre el producto agropecuario y el consumo de los hogares [@engle_granger1987]

Para ello, se aplican pruebas de quiebres estructurales con el fin de identificar posibles cambios en la tendencia de largo plazo del producto agropecuario. Posteriormente, se analiza la dinámica del producto agropecuario como respuesta a cambios institucionales asociados a las reformas agrarias, utilizando un modelo de proyecciones locales que permite estimar sus efectos en distintos horizontes de tiempo. Las reformas se consideran eventos puntuales, lo que facilita identificar tanto su impacto inmediato como sus efectos rezagados sobre el desempeño del sector.

Posteriormente se analizará la cointregación entre el producto agropecuario y el consumo de los hogares, con el fin de identificar si existe una relación de largo plazo entre estas variables, lo que permitiría inferir que las reformas agrarias no solo afectan la producción agrícola, sino también el bienestar de los hogares colombianos.

------------------------------------------------------------------------

# Estructura agraria y productividad: fundamentos teóricos

En este apartado se analizarán a detalle cada una de las reformas agrarias, los contextos en los cuales fueron promulgadas y los impactos en el sector rural, de este modo, se podrá observar cuál reforma agraria si tuvo un impacto relevante.

## Ley 200 de 1936

La Ley 200 de 1936 introdujo el principio de la “función social de la propiedad”, estableciendo que la tierra debía cumplir un uso económico efectivo. La reforma redefinió la naturaleza de la propiedad rural al vincularla directamente con su explotación productiva. Adicionalmente, se establecieron mecanismos institucionales para sancionar la tenencia improductiva, incluyendo la extinción de dominio en casos de abandono de 5 años. La ley también creó una jurisdicción especial de jueces de tierras, los cuales podrían reconocer a los campesinos como dueños de la tierra por encima de los propietarios, y estableció mecanismos como la prescripción adquisitiva para campesinos que explotaran tierras de buena fe. En conjunto, estas disposiciones trasladaron los conflictos agrarios desde formas de confrontación directa hacia escenarios institucionales mediados por el Estado [@ley2001936, @marulanda1989].

Desde una perspectiva económica, la ley introdujo incentivos generalizados para que los actores rurales produjeran y dieran un uso eficiente a la tierra, además de penalizar su desuso, impulsado por la redefinición de la propiedad rural. Sin embargo, esta reforma agraria careció de un carácter distributivo significativo: no incorporó mecanismos mediante los cuales el Estado o la sociedad pudieran llevar a cabo una redistribución generalizada de la tierra, y se limitó a casos específicos en los que las condiciones para la redistribución eran poco probables. En particular, a los campesinos se les podía despojar de las tierras antes de cumplir los cinco años establecidos. Esto, al no revertir el proceso de concentración de la tierra, permitió que se profundizaran tanto el conflicto por la tierra como la improductividad [@navarrete2017, @marulanda1989]

## Ley 135 de 1961

La Ley 135 de 1961 introdujo una reforma agraria enfocada en la redistribución de la tierra. Esta reforma, implementada durante la primera presidencia del Frente Nacional, priorizó la tenencia de tierra para campesinos que no la poseían, favoreciendo a las personas cuyo trabajo estaba relacionado con la explotación de la tierra. Para ello, se creó el Instituto Colombiano de la Reforma Agraria (INCORA) como principal mecanismo estatal de la política pública. Este realizaba extinciones de dominio sobre tierras incultas y la expropiación de predios según su uso: predios sin explotación productiva, es decir, en desuso; con un uso inadecuado del cultivo; o, bajo ciertas condiciones de interés general, incluso en algunos casos cuando existía un adecuado cultivo.

Además, el INCORA tenía como objetivo la eliminación de los minifundios, que en esencia son poco productivos debido al reducido tamaño que representan. Con todo esto, se buscaba poner fin a los conflictos rurales y mejorar la calidad de vida de los campesinos[@duff1966].

A pesar de los esfuerzos realizados, la reforma agraria sufrió de una implementación deficiente. En 1962–1963, el país enfrentó una caída en los precios internacionales del café, lo que llevó a que el INCORA pasara de un presupuesto de 100 millones de pesos en 1961 a tan solo 20 millones en 1963 (cita). Esto, sumado a las críticas de grupos conservadores por la expropiación de tierras, e incluso a críticas de sectores liberales por el pago de indemnizaciones a los propietarios, llevó a que la reforma agraria no cumpliera con sus objetivos y a que se profundizara el conflicto por la tierra [@c1998cuestión]

INCORA desde su nacimiento hasta su desaparición en 1999, adquirió 839.793 hectáreas representando el 2,7% de la frontera agrícola del país y extinguió el derecho dominio sobre 3.621.289 hectáreas, lo que representa el 11,7% de la frontera agrícola del país [@gutierrez2023], esto fue un esfuerzo importante, pero insuficiente  para revertir la concentración de la tierra, y por ende, el conflicto por esta.





## Ley 160 de 1994

La Ley 160 de 1994, promulgada en el contexto de la Constitución de 1991, introdujo una reforma agraria orientada en la redistribución de la tierra y los servicios complementarios. Esta reforma se implementó durante la presidencia de César Gaviria Trujillo y se enfocó en la redistribución de tierras a través de mecanismos de compra, expropiación y adjudicación, con el objetivo de beneficiar a los campesinos sin tierra o con tierras insuficientes. Además, se establecieron programas de apoyo para mejorar la productividad y las condiciones de vida de los beneficiarios, incluyendo acceso a crédito, asistencia técnica y servicios de extensión agrícola.

Esta reforma agraria trajo consigo una serie de cambios institucionales, incluyendo el reconocimiento del mercado de la tierra como un mecanismo para la redistribución, lo que implicó un mercado regulado mas no controlado por el Estado, de la creación de un sistema de descentralización hacia los departamentos y municipios para la implementación de la reforma y la participación de organizaciones campesinas en la formulación y ejecución de las políticas agrarias. Sin embargo, a pesar de estos esfuerzos, la reforma enfrentó desafíos significativos en su implementación, incluyendo la falta de recursos financieros, la resistencia de los propietarios de tierras y la persistencia de la violencia rural, lo que limitó su impacto en la reducción de la concentración de la tierra y en la mejora de las condiciones de vida de los campesinos [@c1998cuestión].

A pesar de los esfuerzos realizadas, la agricultura colombiana sufrió un duro golpe con la apertura económica de 1991, lo que llevó a una caída en la producción agrícola y a un aumento en las importaciones de productos agrícolas, debido a que el país paso de un arancel de 31,5% antes de 1991 a un arancel del 15% en 1994, lo que llevó a que el sector agrícola se viera afectado por la competencia internacional [@coyuntura1999]. Esto, sumado a la falta de recursos financieros para la implementación de la reforma, la resistencia de los propietarios de tierras y la persistencia de la violencia rural, limitó su impacto en la reducción de la concentración de la tierra y en la mejora de las condiciones de vida de los campesinos [@c1998cuestión]. 

## Reforma agraria derivada del Acuerdo de Paz con las FARC-EP en 2016

La reforma agraria derivada del Acuerdo de Paz con las FARC-EP en 2016, implementada durante la presidencia de Juan Manuel Santos Calderón, introdujo una reforma agraria orientada a la redistribución de la tierra y el desarrollo rural integral. En el primer punto del acuerdo se estableció la necesidad de una reforma rural integral que abordara las causas estructurales del conflicto armado, incluyendo la concentración de la tierra, la pobreza rural y la falta de acceso a servicios básicos [@acuerdo_paz_punto1_2016]. Esta reforma puso como objetivo la redistribución de tres millones de hectáreas de tierra en un plazo de 12 años, beneficiando a campesinos sin tierra o con tierras insuficientes, así como a comunidades étnicas y víctimas del conflicto armado. Además, se establecieron programas de apoyo para mejorar la productividad y las condiciones de vida de los beneficiarios, incluyendo acceso a crédito, asistencia técnica y servicios de extensión agrícola.

Hablar de un fracaso de esta reforma agraria es prematuro, sin embargo, es importante destacar que la persistencia de la violencia rural, la resistencia de los propietarios de tierras y la falta de recursos financieros y estatales para la implementación de los programas de apoyo, han limitado su impacto en la reducción de la concentración de la tierra y en la mejora de las condiciones de vida de los campesinos [@echavarria2025].

# Teoría económica de las tierras y la productividad

El análisis de la relación entre la estructura de tenencia de la tierra y la productividad agrícola se ha abordado desde diversas perspectivas teóricas. La teoría económica sugiere que la concentración de la tierra puede generar ineficiencias productivas debido a problemas de agencia, falta de incentivos para la inversión y el uso eficiente de los recursos, así como a la existencia de economías de escala que pueden favorecer a grandes propietarios en detrimento de pequeños agricultores [@berry1979; @binswanger1995].


Además, la concentración de la tierra puede generar conflictos sociales y políticos, lo que a su vez puede afectar negativamente la productividad agrícola. La falta de acceso a la tierra para los pequeños agricultores puede limitar su capacidad para invertir en mejoras productivas, lo que puede llevar a una menor producción agrícola y a un menor bienestar para las comunidades rurales [@deininger1999].

En contraste, un aumento del consumo de los hogares puede generar incentivos para mejorar la productividad agrícola, ya que una mayor demanda de alimentos puede incentivar a los productores a invertir en mejoras productivas para satisfacer esa demanda [@ruttan_hayami_strategies].


Para entender la causalidad entre las reformas agrarias, la concentración de la tierra, la productividad agrícola y el consumo de los hogares, mostraremos este cuadro conceptual:


```{=latex}
\begin{figure}[H]
\centering
\vspace{-2 cm}

\begin{tikzpicture}[
    every node/.style={draw, rectangle, rounded corners, align=center, minimum width=4cm},
    arrow/.style={->, thick}
]

\node (A) at (0,4) {Reformas Agrarias};
\node (B) at (0,2) {Distribución de la Tierra};
\node (C) at (0,0) {Concentración de la Tierra (Gini)};

\node (D) at (6,0) {Productividad Agrícola};
\node (E) at (6,-2) {Ingreso Rural};
\node (F) at (6,-4) {Consumo de los Hogares};

\node (G) at (-6,0) {Conflicto por la Tierra};

\draw[arrow] (A) -- (B);
\draw[arrow] (B) -- (C);

\draw[arrow] (C) -- (D);
\draw[arrow] (D) -- (E);
\draw[arrow] (E) -- (F);

\draw[arrow] (A) to[bend left=20] (D);
\draw[arrow] (A) to[bend left=130] (E);

\draw[arrow] (C) -- (G);
\draw[arrow] (G) -- (C);

\draw[arrow] (F) to[bend left=85] (D);

\draw[arrow, dashed] (C) to[bend left=15] node[above]{Relación inversa} (D);

\end{tikzpicture}
\caption{Relación conceptual entre reformas agrarias, concentración de la tierra y desempeño económico. Fuente: Adaptado de Berry y Cline (1979); Binswanger, Deininger y Feder (1995); Ruttan y Hayami (1985); Deininger (1999).}

\end{figure}

```
Este marco conceptual sugiere la existencia de múltiples mecanismos que afectan la dinámica del sector agropecuario, lo que hace necesario un análisis empírico que permita identificar la relevancia relativa de cada uno de estos canales.



------------------------------------------------------------------------

# Metodología

En esta sección mostrare como se construyó la serie de tiempo del producto agropecuario y del consumo de los hogares, así como las pruebas de quiebres estructurales, el método de proyecciones locales y el análisis de cointregación.

## Construcción de la serie de tiempo

Se construyó una serie de tiempo del producto agropecuario y del consumo de los hogares en Colombia para el periodo 1925–2025. Para ello, se uso la base ya estructurada por el Banco de la República de Colombia (BRC) y se hizo un proceso de empalme de las series de tiempo disponibles, usando dos métodos:

1. Método de empalme por encadenamiento: Para el periodo de 1950-2025 se usó la serie de tiempo del producto agropecuario y del consumo de los hogares. La serie fue construida a partir de cinco segmentos correspondientes a diferentes años base, utilizando en cada tramo la base más reciente disponible y posteriormente encadenando las tasas de crecimiento entre periodos. La serie final se expresa en términos de la base 2015, garantizando coherencia en niveles y tasas de variación[@banrep_pib].

2. Ajuste del empalme para el periodo 1925-1949: el enpalme de esta serie con el resto del periodo presento una dificultad, la serie de tiempo del producto agropecuario y del consumo de los hogares para el periodo 1925-1949 se constuyo a partir de la base del año 1950, lo que llevó a que el producto agropecuario y el consumo de los hogares para este periodo fueran mayores a los niveles del año base, lo que no es coherente[@banrep_pib]. 
Para solucionar esto, se tomó la tasa de crecimiento de la serie del PIB agregado del BRC constuida a partir de 1905 a 2025 sin desagregar por sectores, y se aplicó esta tasa de crecimiento al producto agropecuario y al consumo de los hogares para el periodo 1925-1949, lo que permitió ajustar los niveles de estas variables para que fueran coherentes con la base del año 1950.
Este procedimiento implicar asumir que el producto agropecuario y el consumo de los hogares crecieron a la misma tasa que el PIB agregado durante el periodo 1949-1950, lo que es una simplificación, pero permite obtener una serie de tiempo coherente para el análisis empírico.

## Pruebas de quiebres estructurales





------------------------------------------------------------------------

# Resultados

Presenta resultados.

------------------------------------------------------------------------

# Conclusiones

Conclusiones finales.

------------------------------------------------------------------------

# Referencias